### PR TITLE
Update sugargame to v1.3

### PR DESCRIPTION
**Pull request by ayushnawal**

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Why are the end of line marks missing from each source file?  The Sugargame sources certainly have end of line marks, so I'm puzzled how this could happen.

Also, have you tested the activity?

**Comment by ayushnawal** [comment]
Thanks for the review. I have added empty lines at the end of each source file and tested the activity again.
Activity is running smoothly with a warning `Activity written for Python 2, consider porting to Python 3` . I will try to port the activity to Python 3.

**Comment by quozl** [comment]
Thanks.  I've tested, but nothing happens when I press Play.  The activity stops working.  This appears in logs;

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/StickHero.activity/main.py", line 695, in make
    if event.type == pygame.KEYDOWN and event.key == 273:
UnboundLocalError: local variable 'event' referenced before assignment
```

```log
1576201090.306673 ERROR root: Event queue full!
Traceback (most recent call last):
  File "/usr/share/sugar/activities/StickHero.activity/sugargame/event.py", line 110, in _quit_cb
    pygame.event.post(pygame.event.Event(pygame.QUIT))
pygame.error: Event queue full
Traceback (most recent call last):
  File "/usr/share/sugar/activities/StickHero.activity/sugargame/event.py", line 107, in _screen_changed_cb
    self.update_display()
  File "/usr/share/sugar/activities/StickHero.activity/sugargame/event.py", line 96, in update_display
    pygame.event.post(pygame.event.Event(pygame.VIDEOEXPOSE))
pygame.error: Event queue full
```

This also happens for me in _master_ branch, so it isn't your change that did it.  However, it must be fixed before I'll merge a patch updating Sugargame.

**Comment by ayushnawal** [comment]
Thanks @quozl for the review. In my system, I tested again and the activity was running smoothly. 
Here's a snapshot I took while testing after updating sugargame.

Screenshot from 2019-12-14 16-35-53

**Comment by quozl** [comment]
Thanks.  I'll wait for you to figure out why it doesn't work for me, and what to do about the variable unassigned.  From a quick look, `event` is defined inside a `for` loop which may not execute, and yet it is used outside the `for` loop.

**Review by srevinsaju — CHANGES_REQUESTED** [review]
@ayushnawal Tested,
* Unable to run the activity. (similar issue as @quozl ) Here are the logs
```
Traceback (most recent call last):
  File "/../stick-hero-activity/sugargame/event.py", line 109, in _screen_changed_cb
    self.update_display()
  File "/../stick-hero-activity/sugargame/event.py", line 98, in update_display
    pygame.event.post(pygame.event.Event(pygame.VIDEOEXPOSE))
pygame.error
Traceback (most recent call last):
  File "/run/media/ss/ARCH_DATA/git/stick-hero-activity/main.py", line 695, in make
    if event.type == pygame.KEYDOWN and event.key == 273:
UnboundLocalError: local variable 'event' referenced before assignment
```
* Resize the activity to match display size

**Comment by ayushnawal** [comment]
Although I was not getting this error but fixed it using your traceback.
Also, I tried to match the semantics used for sugargame v1.3 by removing sys.exit calls.

Took me an hour to fix :cry: . same as `make-them-fall-activity`, Although the approach is different because the same approach wouldn't have worked here.

@srevinsaju @quozl  please review

**Comment by srevinsaju** [comment]
Thanks @ayushnawal , will test it asap

**Comment by ayushnawal** [comment]
@srevinsaju gentle reminder

**Comment by quozl** [comment]
Tested 96b4550 on a VM.  The game would not play; the stick was always the same length, as if the key event handling is broken.  _master_ branch tested; it plays correctly.

Looking briefly at the event handling, it looks like you changed from pygame.event.get to pygame.event.poll, which means only one event is handled every 60th of a second.

**Comment by ayushnawal** [comment]
> you changed from pygame.event.get to pygame.event.poll

I changed it to avoid any UnboundLocalError due to `event` referenced outside for loop.

Looked back at the code, now the while loop will continue when it is a none type event. 

Tested, looks good to me.

**Comment by quozl** [comment]
Events must be completely handled before pausing for clock, otherwise the event queue may be filled.

**Comment by ayushnawal** [comment]
using `event.get()` now.

Also fixed the UnboundLocalError for event which was occuring before.

@quozl please review

**Comment by quozl** [comment]
As at 2853409 your code creates an empty event, then gets all events on the queue and discards all but the last event.

So if the event queue is empty when pygame.event.get is called, the rest of the function isn't troubled by _event_ being undefined, as it would otherwise be.  An odd way to do things.

But to discard all but the last event is wrong.  Why would you do that?

Not surprisingly, the game does not properly respond to keys.

**Comment by quozl** [comment]
See https://github.com/sugarlabs/stick-hero-activity/pull/29

**Pull request closed without merging**
